#include<iostream>
#include<stdio.h>
#include "node.hpp"

#define YYDEBUG 0

extern int yyparse();
extern Node* rootNode;

std::string getCompilationOutput();

int main(int argc, char **argv)
{
    if ((argc > 1) && (freopen(argv[1], "r", stdin) == NULL))
    {
        std::cerr << argv[0] << ": File " << argv[1] << " cannot be opened.\n";
        return -1;
    }

#if YYDEBUG == 1
    extern int yydebug;
    yydebug = 1;
#endif

    yyparse();

    std::cout<< getCompilationOutput() <<std::endl;

    return 0;
}

std::string getCompilationOutput()
{
    std::string output = "";

    output += "/* CODE GENERATED BY GCHC */\n\n";
    output += "#include<iostream>\n";
    output += "#include<string>\n";
    output += *(rootNode->value);

    return output;
}
